### ISSUE TITLE
The NeoIntegrationCli process having errors and not exiting

### ISSUE THREAD

**Issue by kvegter** [neo4j-contrib/neo4j-etl#10]
I was testing with an oracle HR example database (SDP_VM), and there where errors in the NeoIntegrationCli process and they were not shown in the etl-gui. In fact the etl-gui remains in the same initial state. Only after I killed the process then I saw the output of the NeoIntegrationCli in the etl-gui.
This was in ETLApp 0.0.13 and Neo4jDesktop 1.0.13 (1.0.13.477)

- The NeoIntegrationCli process did not 'exited' on error

- So no output of the NeoIntegrationCli is shown in etl-gui while it is processing (or the error occurs to fast and freezes the process).

**Comment by albertodelazzari** [comment]
Error messages have been improved so please try the latest version of Neo4jDesktop and ETL tool
