### ISSUE TITLE
It must be possible to give the neo4j username and password in the etl-gui

### ISSUE THREAD

**Issue by kvegter** [neo4j-contrib/neo4j-etl#11]
When you create in the Neo4jDesktop a db, it creates it without setting a username/password. As soon as you open the browser it asks to reset the password. So we need the possibility to give a neo4j username and password in the etl-gui.

**Comment by albertodelazzari** [comment]
Neo4j username and password are now automatically retrieved by using the Neo4j Desktop API so there is no need to give them
