### ISSUE TITLE
Cypher query for importing data needs to be fixed for windows paths

### ISSUE THREAD

**Issue by lju-lazarevic** [neo4j-contrib/neo4j-etl#14]
Cypher query for importing data needs to be fixed for windows paths in load-csv.cypher. For example:
LOAD CSV FROM 'file:///csv-016\northwind/NODE_northwind.products_02e6d3c7-d906-4031-93cb-ee12ce8b20ca.csv'

**Comment by omarlarus** [comment]
solved with release 1.2.0
