### ISSUE TITLE
Error exporting from RDBMS to CSV

### ISSUE THREAD

**Issue by bluvoice** [neo4j-contrib/neo4j-etl#2]
My steps:

- Generating metadata mapping...
./bin/neo4j-etl postgresql generate-metadata-mapping --host myhost --port 5432 --user myuser --password 'mypassword' --database mydb > /tmp/ilikeit/mapping.json

- Creating options.json...
echo '{"multiline-fields":"true"}' > /tmp/ilikeit/options.json

- Exporting from RDBMS to CSV...
./bin/neo4j-etl postgresql export --host myhost --port 5432 --user myuser --password 'mypassword' --database mydb --destination $NEO4J_HOME/data/databases/graph.db/ --import-tool $NEO4J_HOME/bin --csv-directory /tmp/ilikeit --mapping-file /tmp/ilikeit/mapping.json --options-file /tmp/ilikeit/options.json --debug --force --quote '"'

The output is:

![errorneo4jetl](https://user-images.githubusercontent.com/7498638/30283519-a0ed9d7c-9718-11e7-81c3-552cfa4ea150.JPG)

I see that in mapping.json it is added a prefix "null." to original table name. 
In fact, in the attached output I see "ERROR: relation "null.ilk_user_accounts" does not exist", but my postgresql table name is ilk_user_accounts, not null.ilk_user_accounts.

Can you help me?

**Comment by albertodelazzari** [comment]
Hi @bluvoice, it seems that the tool is not reading the schema name properly. Are you using a specific schema or the public one?
Meanwhile you can also try to specify the schema name with the `--schema` option (for example `--schema myschemaname`

**Comment by bluvoice** [comment]
Hi @albertodelazzari, I've tried to specify the schema name but the result is a empy mapping.json file.

Then, I've tried to replace in the mapping.json the string "null" with the name of db and to execute the step for exporting data to csv and importing them into graph db. The result of command is without errors, but it doesn't build relationships but only nodes.

**Comment by albertodelazzari** [comment]
Can you try to run the following commands and paste the results?

Access sql console with `sql -U username`

Run the following commands:

`\l` --> (list of databases)
`\dn` -->  (list of schemas)

This will help us to better understand how you Postgres instance is and to replicate you issue
Thanks

**Comment by bluvoice** [comment]
Sorry, but I'm not authorized to share many info about db instance.

What part of the results do you need?

**Comment by albertodelazzari** [comment]
@bluvoice I can share with you a build "preview" of the next release where probably your issue doesn't exist. I think it's worth a try. You can contact me at alberto.delazzari@larus-ba.it and I'll send you a link in order to download the package

**Comment by jexp** [comment]
@bluvoice ping?
