### ISSUE TITLE
Neo4j ETL UI cannot save mapping

### ISSUE THREAD

**Issue by bobbachand** [neo4j-contrib/neo4j-etl#21]
Hi Feedback,

I have run into an issue with the ETL UI wizard. I can connect and map relational database to graph but when I get to the  “Explore and change your metadata” page I cannot save using the “Save Mapping” button and the "Next" button does not become active.

Example screen capture and I have tried this on two different databases.
![image](https://user-images.githubusercontent.com/8195616/41294003-8e8ed7aa-6e1c-11e8-9ae7-dcd8e7eeb5a3.png)

**Comment by jexp** [comment]
Hi Bob,

can you check the following:

- there is a log file written to the "import" directory of your database

- enable developer mode in neo4j desktop
- reload / restart neo4j-etl
- there should be a developer tools button on top
- click that and check/share the JS console (make sure to remove any credentials/addresses)

Thanks

**Comment by bobbachand** [comment]
Thanks, here is the log from the developer console.
[neo4-etlError.log](https://github.com/neo4j-contrib/neo4j-etl/files/2098362/neo4-etlError.log)

**Comment by bobbachand** [comment]
Was this what you need?

**Comment by albertodelazzari** [comment]
@bobbachand if you're using the ETL tool on windows, we resolved an issue related to the "next" button. In the next release, it will be fixed.

**Comment by bobbachand** [comment]
Thanks Alberto, any estimate on when this will be released?

**Comment by alphen87** [comment]
I would also like to know when the next version will be released, I am having the same issue with mapping larger schemas at the moment. When I tried this on a simple MySQL test database with 2 tables and 1 foreign key, it seems to be working fine.

**Comment by jexp** [comment]
Releasing today.

**Comment by bobbachand** [comment]
Thanks, the issue has been resolved.
