### ISSUE TITLE
Blank screen after selecting MS SQL driver on ETL v 1.3.1

### ISSUE THREAD

**Issue by michaeljquinn** [neo4j-contrib/neo4j-etl#35]

**Comment by michaeljquinn** [comment]
The bug is definately in the file selection dialog, where jdbc driver from file system is selected. Oracle, MS SQL, DB2 and jdbc all behave in the same manner

**Comment by michaeljquinn** [comment]
also tried the download link on the etl site here in github - sqljdbc42, same behaviour, definately a problem with non built in drivers, where does the config file get generated ?

**Comment by michaeljquinn** [comment]
re-opened, got closed by accident

**Comment by conker84** [comment]
@michaeljquinn thanks a lot for reporting this!
We are investigating and we'll give feedback ASAP.

**Comment by michaeljquinn** [comment]
Michael Quinn again
anyone home ??, seriously - any progress on this 
cheers

**Comment by michaeljquinn** [comment]
oops, sorry, just saw the update, thanks

**Comment by michaeljquinn** [comment]
got 1.3.2 now all working good - close this 
thanks heaps
