### ISSUE TITLE
ETL-tool has does not load version 1.4.1

### ISSUE THREAD

**Issue by teuno** [neo4j-contrib/neo4j-etl#55]
With ETL tool 1.4.1 and browser 3.3.20 the ETL tool does not load. I tryed it in a new project and an old project. No difference. The console looks like this.
![image](https://user-images.githubusercontent.com/25672590/65413650-3014bb80-ddf2-11e9-96b1-0edd4fca263e.png)

Any ideas how this happens?

**Comment by jexp** [comment]
But it updated to 1.4.1?

Do you have projects with databases already in your desktop?

**Comment by teuno** [comment]
Yes, but there it did not work either, so I tryed it in a new project.

**Comment by jexp** [comment]
Which version of Desktop do you use? I have 1.2.1

**Comment by teuno** [comment]
I have the same version.

**Comment by teuno** [comment]
I found my problem. Apparently an java_options environment variable ( -Xmx512M) I did not think would do anything made sure I the gui didn't load.
