### ISSUE TITLE
Large PostgreSQL not showing for editing

### ISSUE THREAD

**Issue by smatovski** [neo4j-contrib/neo4j-etl#62]
The database maps but when I click next all I get is a blank screen. PostgreSQL db has 472 tables so it pretty large.

**Comment by jexp** [comment]
Can you share your logs or any messages from the JS console?

You can run the etl-tool after enabling "developer mode" in Neo4j Desktop settings (at the bottom)
Then you should have a button on top for "Developer Tools"
Please share any errors that occurr there.

Besides the 500 tables, how many FKs do you have? Any other odd indexes/constraints/types/constructs?
Would it be possible to share the postgres schema to reproduce?

**Comment by smatovski** [comment]
Consoles are not showing any errors. Attaching mapping log and postgresql backup file from pgAdmin.
[ETL_Log.txt](https://github.com/neo4j-contrib/neo4j-etl/files/3889673/ETL_Log.txt)
[schema.txt](https://github.com/neo4j-contrib/neo4j-etl/files/3889803/schema.txt)
