### ISSUE TITLE
MSSQL and JDBC driver

### ISSUE THREAD

**Issue by BrianKrohn** [neo4j-contrib/neo4j-etl#64]
I put the mssql jdbc driver in my C:\Program Files\Neo4j Desktop\resources\lib folder, but the ETL tool complains that "Connection failed. No suitable driver for the connection"

I am on Windows 10, using the ETL UI with Neo4j desktop, and the MS JDBC driver: https://www.microsoft.com/en-us/download/details.aspx?id=55539

I am using a MS SQL named instance.  My connection URL is:
jdbc:sqlserver://MYSERVER\MYINSTANCE;databaseName=MYDATABASE

I've also tried:
jdbc:sqlserver://MYSERVER;instanceName=MYINSTANCE;databaseName=MYDATABASE

**Comment by conker84** [comment]
Hi @BrianKrohn,
Do you selected the JDBC driver in the area highlighted in red?
<img width="1657" alt="Schermata 2020-01-17 alle 10 44 54" src="https://user-images.githubusercontent.com/1833335/72601867-8ca66400-3916-11ea-9b5f-9eaf73de7e75.png">

**Comment by BrianKrohn** [comment]
I hadn't.  That did the trick.  Thanks.
