### ISSUE TITLE
ETL tool 1.3.1 doesn't work with Neo4j 4.0.0 in bolt mode

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-etl#65]
Subject says it all :-)

**Comment by jexp** [comment]
Also need to check import tool. I think they removed the `neo4j-import` and we need to switch to neo4j-admin import - where they also broke the CLI API in 4.0 vs. 3.x so we need version switches :(

But bolt mode should go first

**Comment by jexp** [comment]
Should be fixed in 1.5.x
