### ISSUE TITLE
Every field from MYSQL mapped to strings

### ISSUE THREAD

**Issue by abs-zero** [neo4j-contrib/neo4j-etl#7]
When I tried to import with `--using cypher:direct`, every field from MYSQL database got imported as strings in neo4j database. But imports is fine with correct data types if done without `--using cypher:direct`. 
Is this a bug?

**Comment by inserpio** [comment]
Hi @abs-zero, just confirmed on slack that it's indeed a bug as we don't manage the "neo4j-data-type" properly when you use all 3 non-bulk --using options.

**Comment by inserpio** [comment]
@AngeloBusato @albertodelazzari CsvNode and CsvRelationship need to check the "neo4j-data-type" field and manage type conversion accordingly (toInt, toFloat) as LOAD CSV by default imports as String...

**Comment by abs-zero** [comment]
Are there any updates?

**Comment by albertodelazzari** [comment]
@abs-zero in a couple of day we will do a new release with the fix for your issue

**Comment by abs-zero** [comment]
Booleans are still not mapped properly with `--using cypher:direct`

**Comment by jexp** [comment]
@abs-zero Which version do you use?

**Comment by abs-zero** [comment]
neo4j-etl-cli-1.2.0-RC1

**Comment by abs-zero** [comment]
For more context, I am mapping `TINYINT` of mysql to `Boolean` in neo4j. This works fine without `--using cypher:direct`.

**Comment by inserpio** [comment]
Hi @abs-zero, I confirm we're not managing TINYINT properly using all 3 cypher approaches.
Will mark this issue as a BUG and start working on it just right now.
