### ISSUE TITLE
CLI ETL tool concats import path with csv-directory using Docker

### ISSUE THREAD

**Issue by zackgow** [neo4j-contrib/neo4j-etl#73]
path in `docker-compose`: 
```
volumes:
  - ./neo4j/import:/$NEO4J_HOME/import
```

running export tool:
```
./etl-cli/bin/neo4j-etl export \
  --rdbms:url jdbc:postgresql://postgres:$DATABASE_PORT/$DATABASE_DB?ssl=false \
  --rdbms:schema public \
  --rdbms:password $DATABASE_PWD \
  --rdbms:user $DATABASE_USER \
  --neo4j:url bolt://localhost:$NEO4J_PORT \
  --neo4j:user $NEO4J_USER \
  --neo4j:password $NEO4J_PWD \
  --import-tool $NEO4J_HOME/bin \
  --destination $NEO4J_HOME/data/databases/neo4j \
  --csv-directory $NEO4J_HOME/import \
  --config-file $NEO4J_HOME/tmp/postgres_neo4j.config \
  --output-mapping-file=$NEO4J_HOME/tmp/mapping.json \
  --mapping-file=$NEO4J_HOME/tmp/mapping.json
```

yields:
```
- CSV directory: /var/lib/neo4j/import/csv-001
- Writing CSV headers for node NODE_public.t1_33ed0167-5b49-4a88-b3ec-ede6868d6163
- Writing CSV headers for node NODE_public.t2_74758fef-503c-4365-adc9-561fc7348b4c
- Writing CSV headers for relationship REL_t2_17c659d5-4491-4578-9847-6823193db52a
Export time: 0.714 (s)
- Creating Neo4j store from CSV...
- Direct driver instance 873175411 created for server address localhost:7687
- Closing driver instance 873175411
- Closing connection pool towards localhost:7687
org.neo4j.driver.exceptions.ClientException: Couldn't load the external resource at: file:/var/lib/neo4j/import/var/lib/neo4j/import/csv-001/public/NODE_public.t2_74758fef-503c-4365-adc9-561fc7348b4c.csv
```
Looking at the relevant portion of the generated Cypher script:
```LOAD CSV FROM 'file:////var/lib/neo4j/import/csv-001/public/```

I realize that the `file:///` refers to the set import directory. However, no matter what combination I do of import directory in docker-compose and csv-directory arg for the command line tool, these get concatenated. If I change the csv-directory arg to be a dummy folder like `test`, the cypher script says:
```LOAD CSV FROM 'file:///test/csv-001/public/NODE_public.t2_74758fef-503c-4365-adc9-561fc7348b4c.csv'```; but `test` is NOT a subdirectory of `import/`, and thus the export tool produces:
```
org.neo4j.driver.exceptions.ClientException: Couldn't load the external resource at: file:/var/lib/neo4j/import/test/csv-001/public/NODE_public.t2_74758fef-503c-4365-adc9-561fc7348b4c.csv
```

Is this just an issue of incorrectly setting the import paths?

**Comment by jexp** [comment]
You need to have the same import folder that is also mapped into your Docker image at `-v /path/to/import/folder/external:/import`

Or can you add a symlink?

Otherwise you could use the "remote/online" connection not the "local/offline one".

**Comment by zackgow** [comment]
Thanks! We ended up going with your second suggestion.
