### ISSUE TITLE
Error importing data from postgres to neo4J ETL tool

### ISSUE THREAD

**Issue by vga91** [neo4j-contrib/neo4j-etl#93]
## Expected Behavior (Mandatory)

The constraints should be imported correctly

## Actual Behavior (Mandatory)

Unable to execute Query: Invalid constraint syntax, ON and ASSERT should not be used. Replace ON with FOR and ASSERT with REQUIRE

## How to Reproduce the Problem

See https://stackoverflow.com/questions/75522318/error-importing-data-from-postgres-to-neo4j-etl-tool

- Running ETL on Neo4j 5.3.0
- Try to import from a postgres sql with primary keys, in order to create constraints (most likely the error also occurs with other db, such as mysql)
- Get the constraint error

Presumably it happens because the neo4j-etl constraint handler leverage a no longer valid syntax, i.e. `"CREATE CONSTRAINT ON .. ASSERT ..."`.

The syntax for neo4j 5.x should be changed to `"CREATE CONSTRAINT FOR ... REQUIRE..."`.

Currently used versions

### Versions

  - Neo4j: 5.3.0-enterprise

**Comment by Form1ca** [comment]
same error neo4j desktop 1.5.9
neo4j-etl-ui
1.6.0
